Changed the styling for the info page
MilRav/zeeslagMD pull request #20
Opened 2023-06-15 14:14 UTC by britneyspoel

* ships different colors
* return button moved to different place

2023-06-16 08:59 UTC, krispijn requested changes
Over de SVGs: het is beter om de kleur via de css te veranderen en niet de SVG brondata te  wijzingen. Als we ergens deze svg's ongestyled worden die nu beinvloed. Daarnaast als we de kleuren willen aan te passen, moeten we dat nu op meerdere plekken doen ipv. 1 css variable aanpassen.

Voorstel: gebruik een css selector voor de info pagina. 

Voorbeeld voor een onderzeeer:
`.shipInfoContainer .submarine #omtrek {
  fill: var(--color-submarine);
}`

2023-06-19 12:48 UTC, britneyspoel commented
>

2023-06-19 14:32 UTC, britneyspoel commented
Ik heb ze nu allemaal veranderd en de hover bij gewerkt.

2023-06-19 14:45 UTC, krispijn commented
Oeps.. verkeerde knop

2023-06-19 14:47 UTC, krispijn approved these changes

2023-06-20 06:53 UTC, merged